import { useEffect, useState } from 'react';
import { Clipboard, Copy, Search, Trash2 } from 'lucide-react';
import { AppShell, PageHeader } from '@/components/app-shell';
import { readHistory, removeGeneration, TOOL_META } from '@/lib/creatorflow';
import type { Generation } from '@workspace/api-client-react';

export default function History() {
  const [history, setHistory] = useState<Generation[]>([]);
  const [query, setQuery] = useState('');
  useEffect(() => setHistory(readHistory()), []);
  const filtered = history.filter((item) => `${item.headline} ${item.summary} ${item.tool}`.toLowerCase().includes(query.toLowerCase()));
  const deleteItem = (id: string) => { removeGeneration(id); setHistory(readHistory()); };
  const copyItem = async (item: Generation) => { await navigator.clipboard?.writeText(item.rawText || item.summary); };
  return <AppShell><PageHeader eyebrow="Local archive" title="Keep the good work close." description="Everything you generate here stays on this device until you choose to clear it." /><div className="px-5 py-7 sm:px-8 lg:px-12 lg:py-10"><div className="mb-7 flex max-w-md items-center gap-3 rounded-xl border border-[hsl(var(--border))] bg-card px-3.5 py-2.5"><Search size={16} className="text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search your archive" className="w-full bg-transparent text-sm outline-none" data-testid="input-search-history" /></div>
    {filtered.length ? <div className="space-y-3">{filtered.map((item) => <article key={item.id} className="group rounded-2xl border border-[hsl(var(--border))] bg-card p-5 transition hover:border-[hsl(var(--primary)/.4)] hover:shadow-[var(--shadow-sm)]" data-testid={`card-history-${item.id}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[hsl(var(--primary)/.1)] px-2.5 py-1 font-mono-app text-[9px] uppercase tracking-[.1em] text-[hsl(var(--primary))]">{TOOL_META[item.tool]?.label || item.tool}</span><span className="text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</span></div><h2 className="font-display text-lg font-bold tracking-[-.03em]">{item.headline}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground">{item.summary}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => copyItem(item)} className="inline-flex items-center gap-1.5 rounded-lg border border-[hsl(var(--border))] px-3 py-2 text-xs font-semibold text-muted-foreground hover:bg-muted hover:text-foreground" data-testid={`button-copy-history-${item.id}`}><Copy size={14} />Copy</button><button onClick={() => deleteItem(item.id)} className="rounded-lg border border-[hsl(var(--border))] p-2 text-muted-foreground hover:bg-[hsl(var(--destructive)/.1)] hover:text-[hsl(var(--destructive))]" aria-label="Delete generation" data-testid={`button-delete-history-${item.id}`}><Trash2 size={15} /></button></div></div><details className="mt-4 border-t border-[hsl(var(--border))] pt-3"><summary className="flex cursor-pointer items-center gap-2 text-xs font-bold text-[hsl(var(--primary))]"><Clipboard size={14} />Review generated content</summary><div className="mt-3 space-y-3">{item.items?.map((content, index) => <div key={index} className="rounded-xl bg-[hsl(var(--muted)/.38)] p-3"><p className="text-sm font-bold">{content.title}</p><p className="mt-1 whitespace-pre-line text-sm leading-6 text-muted-foreground">{content.body}</p></div>)}</div></details></article>)}</div> : <div className="rounded-2xl border border-dashed border-[hsl(var(--border))] px-6 py-16 text-center"><p className="font-display text-lg font-bold">No saved generations yet.</p><p className="mt-2 text-sm text-muted-foreground">Your best ideas will collect here as you work.</p></div>}</div></AppShell>;
}