import { useEffect, useState } from 'react';
import { Check, Moon, Save, Sun } from 'lucide-react';
import { AppShell, PageHeader } from '@/components/app-shell';
import { readPrefs, savePrefs } from '@/lib/creatorflow';

export default function Settings() {
  const [dark, setDark] = useState(false);
  const [platform, setPlatform] = useState('YouTube');
  const [tone, setTone] = useState('Clear and energetic');
  const [audience, setAudience] = useState('');
  const [saved, setSaved] = useState(false);
  useEffect(() => { const prefs = readPrefs(); setPlatform(prefs.platform || 'YouTube'); setTone(prefs.tone || 'Clear and energetic'); setAudience(prefs.audience || ''); setDark(localStorage.getItem('creatorflow:theme') === 'dark'); }, []);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('creatorflow:theme', dark ? 'dark' : 'light'); }, [dark]);
  const save = () => { savePrefs({ platform, tone, audience }); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <AppShell><PageHeader eyebrow="Workspace settings" title="Set your defaults." description="Small choices here keep every generation closer to your voice." /><div className="max-w-3xl space-y-5 px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <section className="rounded-2xl border border-[hsl(var(--border))] bg-card p-6"><p className="font-mono-app text-[10px] uppercase tracking-[.16em] text-[hsl(var(--primary))]">Appearance</p><h2 className="mt-2 font-display text-lg font-bold">Choose your room light.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={() => setDark(false)} className={`flex items-center gap-3 rounded-xl border p-4 text-left transition ${!dark ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.08)]' : 'border-[hsl(var(--border))]'}`} data-testid="button-theme-light"><Sun size={17} /><span><span className="block text-sm font-bold">Daylight</span><span className="text-xs text-muted-foreground">Warm, paper-like workspace</span></span>{!dark && <Check className="ml-auto text-[hsl(var(--primary))]" size={16} />}</button><button onClick={() => setDark(true)} className={`flex items-center gap-3 rounded-xl border p-4 text-left transition ${dark ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.08)]' : 'border-[hsl(var(--border))]'}`} data-testid="button-theme-dark"><Moon size={17} /><span><span className="block text-sm font-bold">Night shift</span><span className="text-xs text-muted-foreground">Low-light creative control room</span></span>{dark && <Check className="ml-auto text-[hsl(var(--primary))]" size={16} />}</button></div></section>
    <section className="rounded-2xl border border-[hsl(var(--border))] bg-card p-6"><p className="font-mono-app text-[10px] uppercase tracking-[.16em] text-[hsl(var(--primary))]">Creator defaults</p><h2 className="mt-2 font-display text-lg font-bold">Keep the setup out of the way.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-bold">Primary platform</span><select value={platform} onChange={(e) => setPlatform(e.target.value)} className="w-full rounded-xl border border-[hsl(var(--input))] bg-background px-3 py-2.5 text-sm outline-none focus:border-[hsl(var(--primary))]" data-testid="select-default-platform"><option>YouTube</option><option>Instagram</option><option>TikTok</option><option>LinkedIn</option><option>Podcast</option></select></label><label><span className="mb-2 block text-xs font-bold">Default tone</span><select value={tone} onChange={(e) => setTone(e.target.value)} className="w-full rounded-xl border border-[hsl(var(--input))] bg-background px-3 py-2.5 text-sm outline-none focus:border-[hsl(var(--primary))]" data-testid="select-default-tone"><option>Clear and energetic</option><option>Warm and candid</option><option>Sharp and contrarian</option><option>Playful and smart</option><option>Calm and instructional</option></select></label></div><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Usual audience</span><input value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="Independent creators building a durable body of work" className="w-full rounded-xl border border-[hsl(var(--input))] bg-background px-3 py-2.5 text-sm outline-none focus:border-[hsl(var(--primary))]" data-testid="input-default-audience" /></label><button onClick={save} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))] transition hover:-translate-y-0.5" data-testid="button-save-settings">{saved ? <Check size={15} /> : <Save size={15} />}{saved ? 'Saved' : 'Save defaults'}</button></section>
    <p className="font-mono-app text-[10px] leading-5 text-muted-foreground">Your preferences and history are stored locally in this browser. Sync arrives when accounts are connected.</p>
  </div></AppShell>;
}